const ENV_VARS = {
  CLOUDINARY_CLOUD_NAME: 'CLOUDINARY_CLOUD_NAME',
  CLOUDINARY_API_KEY: 'CLOUDINARY_API_KEY',
  CLOUDINARY_API_SECRET: 'CLOUDINARY_API_SECRET',
  MONGO_URL: 'MONGO_URL',
  FRONTEND_DOMAIN: 'FRONTEND_DOMAIN',
  JWT_SECRET: 'JWT_SECRET',
  SMTP_HOST: 'SMTP_HOST',
  SMTP_PORT: 'SMTP_PORT',
  SMTP_USER: 'SMTP_USER',
  SMTP_PASSWORD: 'SMTP_PASSWORD',
  SMTP_FROM: 'SMTP_FROM',
  PORT: 'PORT',
  NODE_ENV: 'NODE_ENV',
};

export { ENV_VARS };
